      double precision flux_norm_electron, flux_norm_positron, flux_norm_gamma
      integer ebeam_ncores, ebeam_nexit
      logical ebeam_dofit,ebeam_testplot, ebeampdf
      character *200 ebeampdf_interp_method
      common/bremsstrahlung/flux_norm_electron, flux_norm_positron,flux_norm_gamma,
     &           ebeam_ncores, ebeam_nexit, ebeam_dofit, ebeam_testplot, ebeampdf,
     &		 ebeampdf_interp_method
