      double precision flux_norm, d_target_detector,detector_density,
     &           thetac,theta_aperture,off_axis_depth,
     &           theta_max,
     &		 x_side,y_side,depth
      integer nevts_interaction,ncores
      logical prod_xsec_in_norm,off_axis,cylinder,parallelepiped,testplot
      
      common/fit2D_detector/flux_norm,d_target_detector,detector_density,
     &           thetac,theta_aperture,off_axis_depth,
     &           theta_max,x_side,y_side,depth,nevts_interaction,
     &		 ncores,prod_xsec_in_norm,off_axis,cylinder,parallelepiped,testplot
